(setq phye-elpa-packages
      '(activities
        acp
        agent-shell
        annotate-mode
        atom-dark
        atom-one-dark
        bazel
        better-jumper
        bpftrace-mode
        bufler
        burly
        clipetty
        deadgrep
        dakrone
        dockerfile-mode
        doric-themes
        dorsey
        el-themes
        elisp-autofmt
        emacs-everywhere
        emacsql
        evil-collection
        evil-terminal-cursor-changer
        halloweenie-theme
        hemisu-theme
        hcl-mode
        helpful
        key-chord
        manoj-dark
        markdown-toc
        mermaid-mode
        nerd-icons
        ob-mermaid
        org-fancy-priorities
        org-journal
        org-noter
        org-present
        org-remark
        org-roam
        org-side-tree
        outline-indent
        peep-dired
        pikchr-mode
        popper
        pumpkin-spice-theme
        puni
        rg
        seti-theme
        show-font
        symbol-overlay
        sync-recentf
        tiny
        treemacs
        undo-fu-session
        wombat
        vimish-fold
        zerodark))

(setq melpa-include-packages (append melpa-include-packages phye-elpa-packages nil))

(provide 'phye-init-elpa)
